config/routes.rb
Rails.application.routes.draw do
  root 'home#search'

  get 'search', to: 'home#search'
  get 'search_in_category', to: 'home#search_in_category'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :storage_items
  has_many :availible_in_storages, through: :storage_items, source: :storage

  after_commit :actualize_search_index

  private

  def actualize_search_index
    StorageItem.reindex
  end
end

app/models/storage.rb
class Storage < ApplicationRecord
  has_many :storage_items
end

app/models/storage_item.rb
class StorageItem < ApplicationRecord
  belongs_to :storage
  belongs_to :product

  searchkick language: 'russian'

  def search_data
    {
      product_name:        product.name,
      storage_name:        storage.name,
      product_description: product.description,
      vendor_id:           product.vendor_id,
      quantity:            quantity
    }
  end

  # According to specification empty positions should not be shown in search results,
  # so not adding them to index looks better than filtering results
  def should_index?
    quantity > 0
  end

  def self.categories(terms)
    responce = search(terms, aggregations_params)

    responce.aggs['by_name']['buckets'].map do |bucket|
      OpenStruct.new(name:      bucket['key'],
                     quantity:  bucket['total_qantity']['value'].to_i,
                     doc_count: bucket['doc_count'])
    end
  end

  def self.search_in_category(query, category)
    search(query, where: { product_name: category }, includes: %i[product storage]).results
  end

  def self.aggregations_params
    {
      body_options: {
        size: 0,
        aggs: {
          by_name: {
            terms: { field: :product_name },
            aggs: {
              total_qantity: {
                sum: { field: :quantity }
              }
            }
          }
        }
      }
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def search
    @categories = StorageItem.categories(search_query) if search_query
  end

  def search_in_category
    @results = StorageItem.search_in_category(params[:query], params[:category])
  end

  private

  def search_query
    params.permit(:query)[:query]
  end

  def search_in_category_query
    params.require(:query, :category).permit(:query, :category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_nothing_found.html.haml
.alert.alert-info.text-center
  We search for
  %strong= params[:query] + ','
  but found nothing.

app/views/home/_search_in_category_result.html.haml
%tr
  %td.category_results{colspan: 4 }
    %table.table.nested-table
      %thead
        %tr
          %th #
          %th Name
          %th Description
          %th Vendor ID
          %th Storage
          %th Quantity

      %tbody
        =render results

app/views/home/_search_result.html.haml
%table.table.table-hover
  %thead
    %tr
      %th #
      %th Name
      %th Positions found
      %th Total items quantity

  %tbody
    -categories.each.with_index do |category, i|
      %tr.category.clickable
        %td= i + 1
        %td= category.name
        %td= category.doc_count
        %td= category.quantity
        %td.hidden= link_to 'see all',{ controller: :home, action: :search_in_category, category: category.name, query: params[:query], link_id: category.object_id, remote: true }, id:category.object_id

app/views/home/search.html.haml
#search-container
  #search-form
    = form_tag search_path, method: 'GET', remote: true do
      .col-lg-12
        .input-group
          = text_field_tag :query, params[:query], class: 'form-control'
          %label#search-button.input-group-addon.clickable
            %span.glyphicon.glyphicon-search
            = button_tag '', name: nil, class: 'hidden'

  #loader
  #search-results
    = render 'search_result', categories: @categories unless @categories.blank?

app/views/home/search.js.erb
// set correct request URL in browser in order to get access to results, save link or share
history.pushState({}, '', '<%= request.fullpath %>');

<%if @categories.blank? %>
  $('#search-results').html('<%= j render "nothing_found" %>');
<% else %>
  $('#search-results').html('<%= j render "search_result", categories: @categories unless @categories.blank?%>');
<% end %>

app/views/home/search_in_category.js.erb
$("#<%= params[:link_id] %>").parent().parent().after('<%= j render "search_in_category_result", results: @results %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VhDafTestTask</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/storage_items/_storage_item.html.haml
%tr
  %td= storage_item_counter + 1
  %td= storage_item.product.name
  %td= storage_item.product.description
  %td= storage_item.product.vendor_id
  %td= storage_item.storage.name
  %td= storage_item.quantity